name = "zenathra"
compatibility_date = "2024-06-14"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "zenathra-db"
database_id = "3295e804-87c0-4eb6-8962-dc5796046251"