apiVersion: apps/v1
kind: Deployment
metadata:
  name: candlezone
  namespace: { { .Values.config.namespace } }
spec:
  replicas: 2
  selector:
    matchLabels:
      app: candlezone
  template:
    metadata:
      labels:
        app: candlezone
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
        - name: candlezone
          image: candlezone:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
            - file: .env
              value: 'production'
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 40
            periodSeconds: 90
            timeoutSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 10
            failureThreshold: 3
