import { createEnv } from '@t3-oss/env-nextjs';
import { z } from 'zod';

export const env = createEnv({
  client: {
    NEXT_PUBLIC_GOOGLE_ADS_CLIENT_ID: z.string(),
    NEXT_PUBLIC_HOST_URL: z.string().url(),
  },
  runtimeEnv: {
    ANTHROPIC_API_KEY: process.env.ANTHROPIC_API_KEY,
    ARCJET_API_KEY: process.env.ARCJET_API_KEY,
    AUTH_GITHUB_ID: process.env.AUTH_GITHUB_ID,
    AUTH_GITHUB_SECRET: process.env.AUTH_GITHUB_SECRET,
    AUTH_GOOGLE_ID: process.env.AUTH_GOOGLE_ID,
    AUTH_GOOGLE_SECRET: process.env.AUTH_GOOGLE_SECRET,
    AUTH_MASTODON_ID: process.env.AUTH_MASTODON_ID,
    AUTH_MASTODON_ISSUER: process.env.AUTH_MASTODON_ISSUER,
    AUTH_MASTODON_SECRET: process.env.AUTH_MASTODON_SECRET,
    AUTH_SECRET: process.env.AUTH_SECRET,
    CRON_SECRET: process.env.CRON_SECRET,
    EMAIL_FROM: process.env.EMAIL_FROM,
    FMP_API_KEY: process.env.FMP_API_KEY,
    LOG_LEVEL: process.env.LOG_LEVEL,
    NEXT_PHASE: process.env.NEXT_PHASE,
    NEXT_PUBLIC_GOOGLE_ADS_CLIENT_ID:
      process.env.NEXT_PUBLIC_GOOGLE_ADS_CLIENT_ID,
    NEXT_PUBLIC_HOST_URL: process.env.NEXT_PUBLIC_HOST_URL,
    NODE_ENV: process.env.NODE_ENV,
    RESEND_API_KEY: process.env.RESEND_API_KEY,
    STRIPE_API_KEY: process.env.STRIPE_API_KEY,
    STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
    TEST_PASSWORD: process.env.TEST_PASSWORD,
    TURSO_AUTH_TOKEN: process.env.TURSO_AUTH_TOKEN,
    TURSO_DATABASE_URL: process.env.TURSO_DATABASE_URL,
  },
  server: {
    ANTHROPIC_API_KEY: z.string(),
    ARCJET_API_KEY: z.string(),
    AUTH_GITHUB_ID: z.string(),
    AUTH_GITHUB_SECRET: z.string(),
    AUTH_GOOGLE_ID: z.string(),
    AUTH_GOOGLE_SECRET: z.string(),
    AUTH_MASTODON_ID: z.string(),
    AUTH_MASTODON_ISSUER: z.string(),
    AUTH_MASTODON_SECRET: z.string(),
    AUTH_SECRET: z.string(),
    CRON_SECRET: z.string(),
    EMAIL_FROM: z.string().email(),
    FMP_API_KEY: z.string(),
    LOG_LEVEL: z.string().optional(),
    NEXT_PHASE: z.string().optional(),
    NODE_ENV: z.string().optional(),
    RESEND_API_KEY: z.string(),
    STRIPE_API_KEY: z.string(),
    STRIPE_WEBHOOK_SECRET: z.string(),
    TEST_PASSWORD: z.string(),
    TURSO_AUTH_TOKEN: z.string(),
    TURSO_DATABASE_URL: z.string().url(),
  },
});
